---
server:
  name: kibana
  host: 0.0.0.0

monitoring:
  ui:
    container:
      elasticsearch:
        enabled: true

elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: elastic
