version: "3.8"

services:
  # 注册中心集群
  consul1:
    image: consul
    container_name: consul-node1
    command: agent -server -bootstrap-expect=3 -node=consul-node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
  consul2:
    image: consul
    container_name: consul-node2
    command: agent -server -retry-join=consul-node1 -bootstrap-expect=3 -node=consul-node2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  consul3:
    image: consul
    container_name: consul-node3
    command: agent -server -retry-join=consul-node1 -bootstrap-expect=3 -node=consul-node3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  # 添加对外暴露的节点，启动控制面板 http://localhost:8500/
  consul4:
    image: consul
    container_name: consul-node4
    command: agent -ui -retry-join=consul-node1 -node=consul-node4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    ports:
      - "8500:8500"
    depends_on:
      - consul2
      - consul3
  # 数据库
  mysql-pass:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql-pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  # 链路jaeger http://localhost:16686/
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  # 添加熔断看板 http://127.0.0.1:9002/hystrix
  hystrix-dashboard:
    image: cap1573/hystrix-dashboard
    ports:
      - "9002:9002"